---
title: "Toronto's Reaction to Fight Against Global Warming"
author: 
  - Lantao Cui
thanks: "Code and data are available at: https://github.com/cuilantao/Toronto-s-reaction-to-fight-against-global-warming"
date: "`r format(Sys.time(), '%d %B %Y')`"
abstract: "Climate change and global warming are predominant problems nowadays, in the north pole, polar ice caps are melting at a rate of almost 14% per decade. On top of that, over the past 30 years, the oldest and thickest ice in the north pole has declined by almost 95%. The majority of the Science Community believes that global warming is caused by the excessive emission of greenhouse gases such as Carbon Dioxide and Methane. Luckily, a lot of countries are actively trying to limit the emission of such gases to fight against climate change. In this paper, we will obtain and analyze different Toronto organizations' Energy consumption and Green House Gas emissions from 2011 to 2017. Our findings can help the city government to establish better climate strategies."
output:
  bookdown::pdf_document2
toc: FALSE
bibliography: references.bib
---

# Introduction

Ever since Industrial Revolution, people's life has become more and more convenient, for example, the invention of the steam engine made transportation much more easier. However, this convenience comes with great drawbacks, over the entire industrial revolution, scientist estimated that a total of 2.3 trillion tonnes of Carbon Dioxide have been released into the atmosphere, what is even worse is that those Carbon Dioxide has a life span of 300 - 1000 years, this means that those climate change can happen on the time scale of many generations' lives. The reason those green house gases cause global warming is because they will reflect the heat radiated from Earths' surface back, thus making the Earth warmer. However, hundreds of nations are actively trying to fight against Climate Change, some are planting more trees so that the excessive Carbon Dioxide can be absorbed through Photosynthesis, some are developing more sustainable and environment-free energy source such as solar power. In this paper, we will obtain and analyze different Toronto organizations' Energy consumption and Green House Gas emissions from 2011 to 2017, we aim to find out Toronto's contribution in limiting the emission of green house gases.

# Data

## Data Source

## Methodology and Data Collection

# Results

# Discussion